// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore_for_file: unnecessary_const, require_trailing_commas, document_ignores, public_member_api_docs

import "package:hive_ce/hive.dart";
import "package:khookbook/hive/hive_adapters.dart";

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppPreferencesAdapter());
    registerAdapter(MealDBCategoryCacheAdapter());
    registerAdapter(MealDBCategoryDataAdapter());
    registerAdapter(MealDBCategoryMealDataAdapter());
    registerAdapter(MealDBCategoryMealsCacheAdapter());
    registerAdapter(MealDBMealCacheAdapter());
    registerAdapter(ThemeModeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppPreferencesAdapter());
    registerAdapter(MealDBCategoryCacheAdapter());
    registerAdapter(MealDBCategoryDataAdapter());
    registerAdapter(MealDBCategoryMealDataAdapter());
    registerAdapter(MealDBCategoryMealsCacheAdapter());
    registerAdapter(MealDBMealCacheAdapter());
    registerAdapter(ThemeModeAdapter());
  }
}
